name: Build and Push Docker Image

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version
        id: extract_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Convert Repository Owner to Lowercase
        id: lowercase
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker Image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ibot-gpt:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ibot-gpt:${{ env.VERSION }}

      - name: Build and Push Docker Image to GitHub Container Registry
        run: |
          docker build . --tag ghcr.io/${{ env.REPO_OWNER }}/ibot-gpt:latest
          docker build . --tag ghcr.io/${{ env.REPO_OWNER }}/ibot-gpt:${{ env.VERSION }}
          docker push ghcr.io/${{ env.REPO_OWNER }}/ibot-gpt:latest
          docker push ghcr.io/${{ env.REPO_OWNER }}/ibot-gpt:${{ env.VERSION }}
