name: Build and Push Docker Image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version
        id: extract_version
        run: echo "::set-output name=version::$(cat VERSION)"
      
      - name: Build and Push Docker Image Latest
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ibot-gpt:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ibot-gpt:${{ steps.extract_version.outputs.version }}

      - name: Update VERSION file
        run: |
          NEW_VERSION=$(cat VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo $NEW_VERSION > VERSION
          git config --global user.email "slendymilky@gmail.com"
          git config --global user.name "SlendyMilky"
          git add VERSION
          git commit -m "Bump version to $NEW_VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
